# Generated by Django 3.0.5 on 2020-04-09 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0002_notes_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
