# Generated by Django 3.0.5 on 2020-04-10 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0003_auto_20200409_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='timestamp',
        ),
    ]
