# Generated by Django 3.0.5 on 2020-04-10 05:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0004_remove_notes_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 10, 5, 50, 37, 232334)),
        ),
    ]
