# Generated by Django 3.0.5 on 2020-04-10 05:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0005_notes_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 10, 5, 51, 41, 241692, tzinfo=utc)),
        ),
    ]
