# Generated by Django 3.0.5 on 2020-04-10 05:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0006_auto_20200410_0551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 10, 5, 57, 32, 926922)),
        ),
    ]
