# Generated by Django 3.0.5 on 2020-04-10 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0007_auto_20200410_0557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
