# Generated by Django 3.0.5 on 2020-04-10 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0008_auto_20200410_0612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='description',
        ),
    ]
